Repository openstreetmap/iD, pull requests merged in 2020-09, with the labels that each got.

#7893 Open external links in OSM notes in a new tab
  modules/ui/note_comments.js
Labels: usability

#7816 added function to strip whitespace from searches
  modules/ui/feature_list.js
Labels: usability

#7832 Add portapotty preset
  data/presets.yaml
  data/presets/presets.json
  data/presets/presets/amenity/toilets/disposal/portapotty.json
  data/taginfo.json
  dist/locales/en.json
Labels: preset

#7979 Make the UI scalable for text-only browser zoom
  css/00_reset.css
  css/80_app.css
  modules/ui/feature_list.js
  modules/ui/field_help.js
  modules/ui/fields/check.js
  modules/ui/init.js
  modules/ui/intro/area.js
  modules/ui/intro/building.js
  modules/ui/intro/helper.js
  modules/ui/intro/line.js
  modules/ui/intro/navigation.js
  modules/ui/intro/point.js
  modules/ui/preset_list.js
  modules/ui/scale.js
  modules/ui/sections/background_offset.js
Labels: usability

#7980 [Performance] Calculate height of the textarea instead of letting the browser do it
  modules/ui/sections/raw_tag_editor.js
Labels: performance

#7885 Mapillary improvements and bug fixes
  css/60_photos.css
  modules/services/mapillary.js
  modules/svg/layers.js
  modules/svg/mapillary_images.js
  modules/svg/mapillary_map_features.js
  modules/svg/mapillary_position.js
  modules/svg/mapillary_signs.js
  test/spec/services/mapillary.js
  test/spec/svg/layers.js
Labels: streetlevel

#7991 Support language-specific pluralization
  data/core.yaml
  dist/locales/en.json
  modules/core/localizer.js
  modules/operations/copy.js
  modules/operations/delete.js
  modules/operations/downgrade.js
  modules/operations/extract.js
  modules/operations/paste.js
  modules/operations/split.js
  modules/ui/contributors.js
  modules/ui/panels/history.js
  modules/ui/panels/measurement.js
  modules/ui/sections/changes.js
  modules/ui/sections/entity_issues.js
  modules/ui/sections/validation_issues.js
  modules/validations/disconnected_way.js
Labels: localization

#7995 Fix GPS coordinate searches returning OSM elements
  modules/ui/feature_list.js
Labels: usability

#8012 Enable scaling the selection via hotkeys
  data/core.yaml
  data/shortcuts.json
  dist/locales/en.json
  modules/actions/index.js
  modules/actions/scale.js
  modules/modes/select.js
  modules/ui/zoom.js
  modules/util/keybinding.js
Labels: new-feature

#7829 Help edit menu
  data/core.yaml
  modules/ui/intro/helper.js
  modules/ui/panes/help.js
Labels: walkthrough-help
