Repository openstreetmap/iD, pull requests merged in 2020-05, with the labels that each got.

#7507 Add field for ruins=*
  data/presets.yaml
  data/presets/fields.json
  data/presets/fields/ruins.json
  data/presets/presets.json
  data/presets/presets/historic/ruins.json
  data/taginfo.json
  dist/locales/en.json
Labels: considering, preset

#7514 Added deprecated tags
  data/deprecated.json
Labels: validation

#7510 Custom WMS imagery URL templates
  data/core.yaml
  dist/locales/en.json
  modules/renderer/background_source.js
Labels: enhancement

#7628 Add highlight to multi-select sidebar on hover of entity
  css/80_app.css
  modules/modes/select.js
  modules/ui/sidebar.js
Labels: usability
