Repository openstreetmap/iD, pull requests merged in 2020-02, with the labels that each got.

#7289 Add simple access to advertising
  data/presets/presets/advertising/billboard.json
  data/presets/presets/advertising/board.json
  data/presets/presets/advertising/column.json
  data/presets/presets/advertising/poster_box.json
  data/presets/presets/advertising/totem.json
Labels: considering

#7290 Update QA button strings
  data/core.yaml
  dist/locales/en.json
Labels: localization

#7333 Add upload controller
  modules/core/context.js
  modules/core/index.js
  modules/core/uploader.js
  modules/modes/save.js
  modules/ui/commit.js
  modules/ui/init.js
Labels: api, chore

#7362 Add Osmose translation to contributing guidelines
  CONTRIBUTING.md
Labels: chore-documentation

#7391 Move the "zoom to this" button to the map controls
  css/80_app.css
  data/core.yaml
  dist/locales/en.json
  modules/ui/data_editor.js
  modules/ui/improveOSM_editor.js
  modules/ui/index.js
  modules/ui/init.js
  modules/ui/keepRight_editor.js
  modules/ui/note_editor.js
  modules/ui/osmose_editor.js
  modules/ui/sections/feature_type.js
  modules/ui/zoom_to_selection.js
Labels: usability

#7309 Fix almost junction behaviour for close endpoints
  modules/validations/almost_junction.js
  test/spec/validations/almost_junction.js
Labels: validation
