Repository openstreetmap/iD, pull requests merged in 2021-09, with the labels that each got.

#8685 MapControl scroll
  css/80_app.css
  modules/ui/init.js
Labels: accessibility

#8288 Debounce input events in the preset list.
  modules/ui/preset_list.js
Labels: performance, enhancement

#8689 Removing Maxar standard imagery
  data/imagery.json
  data/manual_imagery.json
  dist/locales/en.min.json
Labels: map-renderer
