Repository openstreetmap/iD, pull requests merged in 2021-01, with the labels that each got.

#8264 Add shortcut to select parent way(s)
  data/core.yaml
  data/shortcuts.json
  modules/modes/select.js
Labels: accessibility, keyboard

#8276 Label route relations with directions and waypoints
  data/core.yaml
  dist/locales/en.min.json
  modules/util/util.js
  test/spec/util/util.js
Labels: field, usability

#8319 Promisify validation
  modules/core/validator.js
  modules/ui/sections/validation_rules.js
  modules/validations/outdated_tags.js
  modules/validations/suspicious_name.js
  modules/validations/unsquare_way.js
  package.json
  test/spec/core/validator.js
Labels: enhancement, validation

#8331 fix typo data/core/yaml in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: chore-documentation
