Repository openstreetmap/iD, pull requests merged in 2021-12, with the labels that each got.

#8839 Object history preservation improvements
  modules/actions/add_member.js
  modules/actions/connect.js
  modules/actions/join.js
  modules/actions/merge.js
  modules/actions/merge_polygon.js
  modules/osm/entity.js
  modules/util/index.js
  modules/util/util.js
  test/spec/actions/add_member.js
  test/spec/actions/connect.js
  test/spec/actions/join.js
  test/spec/actions/merge.js
  test/spec/actions/merge_nodes.js
  test/spec/actions/merge_polygon.js
  test/spec/actions/split.js
  test/spec/osm/entity.js
  test/spec/spec_helpers.js
  test/spec/util/util.js
Labels: priority, enhancement

#8825 fix bug with numeric properties in custom map data
  CHANGELOG.md
  modules/svg/data.js
  modules/ui/sections/raw_tag_editor.js
  test/spec/svg/data.js
Labels: bug

#8834 clear labels for OSM hyperlinks in history panel (OSM history & OSM Profile)
  data/core.yaml
  dist/locales/en.min.json
  modules/ui/panels/history.js
Labels: usability

#8835 Improve UI accessibility - Focus on screen reader support
  CHANGELOG.md
  css/80_app.css
  data/core.yaml
  dist/locales/en.min.json
  modules/renderer/tile_layer.js
  modules/ui/commit.js
  modules/ui/conflicts.js
  modules/ui/data_editor.js
  modules/ui/disclosure.js
  modules/ui/entity_editor.js
  modules/ui/feature_list.js
  modules/ui/field_help.js
  modules/ui/fields/input.js
  modules/ui/fields/localized.js
  modules/ui/fields/roadspeed.js
  modules/ui/geolocate.js
  modules/ui/improveOSM_editor.js
  modules/ui/info.js
  modules/ui/init.js
  modules/ui/keepRight_editor.js
  modules/ui/modal.js
  modules/ui/note_editor.js
  modules/ui/note_header.js
  modules/ui/osmose_editor.js
  modules/ui/pane.js
  modules/ui/panes/help.js
  modules/ui/photoviewer.js
  modules/ui/preset_list.js
  modules/ui/sections/background_display_options.js
  modules/ui/sections/background_offset.js
  modules/ui/sections/map_features.js
  modules/ui/sections/raw_membership_editor.js
  modules/ui/sections/raw_tag_editor.js
  modules/ui/sections/validation_rules.js
  modules/ui/shortcuts.js
  modules/ui/success.js
  modules/ui/tag_reference.js
  modules/ui/tools/modes.js
  modules/ui/tools/notes.js
  modules/ui/tools/sidebar_toggle.js
Labels: accessibility

#8844 Fix incorrect Google validation warnings when viewing esri Africa buildings
  modules/validations/incompatible_source.js
  test/spec/validations/incompatible_source.js
Labels: validation
