Repository openstreetmap/iD, pull requests merged in 2021-11, with the labels that each got.

#8792 improve rendering of turn-restriction boxes in narrow sidebars
  modules/ui/fields/restrictions.js
Labels: bug, field

#8800 clarify "disconnected_way" validation text (fixes #8760)
  data/core.yaml
Labels: validation

#8810 start a running changelog
  CHANGELOG.md
  CONTRIBUTING.md
  RELEASING.md
Labels: chore-documentation

#8803 explicit coloring of preset categories
  CHANGELOG.md
  css/75_categories.css
  modules/ui/preset_icon.js
Labels: icon

#8823 Clarify validator warning about standalone node
  ARCHITECTURE.md
  data/core.yaml
  dist/locales/en.min.json
Labels: usability, validation

#8828 Improve the checking of results from the NSI matcher..
  CHANGELOG.md
  modules/services/nsi.js
Labels: bug, preset, validation
