Repository openstreetmap/iD, pull requests merged in 2022-12, with the labels that each got.

#9399 Update core.yaml
  data/core.yaml
Labels: documentation

#9416 Added highway=busway to 'Traffic Roads' group of map features.
  modules/renderer/features.js
Labels: preset

#9434 Optimize oldTagIssues method
  modules/validations/outdated_tags.js
Labels: performance, validation
