Repository openstreetmap/iD, pull requests merged in 2022-11, with the labels that each got.

#9316 fix the phone input field showing the wrong placeholder
  data/phone_formats.json
  modules/ui/fields/input.js
Labels: bug

#9344 improve combobox fields
  CHANGELOG.md
  modules/services/taginfo.js
  modules/ui/combobox.js
  modules/ui/fields/combo.js
  modules/ui/sections/preset_fields.js
Labels: usability, field

#9375 Upgrade Transifex API and CLI to v3
  .github/workflows/transifex.yml
  .tx/config
  CHANGELOG.md
  dist/locales/ar.min.json
  dist/locales/bg-BG.min.json
  dist/locales/bg@Cyrl.min.json
  dist/locales/br.min.json
  dist/locales/fr.min.json
  dist/locales/index.min.json
  dist/locales/pl.min.json
  dist/locales/zh-TW.min.json
  package.json
  scripts/update_locales.js
Labels: localization, chore-dependency
