Repository openstreetmap/iD, pull requests merged in 2022-07, with the labels that each got.

#9172 fix rendering of proposed bridges
  css/50_misc.css
Labels: map-renderer

#9204 github issue template: Fix link to discussion tab
  .github/ISSUE_TEMPLATE/config.yml
Labels: chore-documentation

#9177 chore: Set permissions for GitHub actions
  .github/workflows/build.yml
  .github/workflows/codespell.yml
Labels: chore

#9141 support incrementing cardinal directions with the up/down buttons
  modules/osm/node.js
  modules/ui/fields/input.js
Labels: field

#9076 Fix iD using invalid user selected imagery
  CHANGELOG.md
  modules/renderer/background.js
Labels: bug

#9057 Update Workflows
  .github/workflows/build.yml
  .github/workflows/codespell.yml
  .github/workflows/transifex.yml
Labels: chore

#8996 Remove double spaces and fix links in Architecture.md
  ARCHITECTURE.md
Labels: chore-documentation
