Repository openstreetmap/iD, pull requests merged in 2023-01, with the labels that each got.

#9446 Address format in Bulgaria
  data/address_formats.json
Labels: localization

#9458 fix: :bug: Fix multiple appending debug vintage unknown label
  modules/renderer/tile_layer.js
Labels: bug

#9443 Fix connect features with uncontrolled crossing
  modules/validations/crossing_ways.js
Labels: validation
