Repository openstreetmap/iD, pull requests merged in 2023-03, with the labels that each got.

#9501 fix inconsistent locale in some parts of iD
  modules/services/nominatim.js
  test/spec/services/nominatim.js
Labels: localization

#9482 Add India address and phone format
  data/address_formats.json
  data/phone_formats.json
Labels: localization

#9492 add 4 tags which imply oneway=yes
  modules/osm/tags.js
Labels: map-renderer

#9493 render right-sided arrows for features with lifecycle prefixes
  modules/osm/way.js
  test/spec/osm/way.js
Labels: map-renderer

#9520 tweak regex when searching for a feature ID
  modules/ui/feature_list.js
Labels: usability

#9546 Update `country-coder` and `location-conflation`
  API.md
  modules/core/LocationManager.js
  modules/ui/fields/address.js
  modules/ui/fields/combo.js
  modules/ui/fields/input.js
  modules/ui/fields/localized.js
  modules/ui/fields/roadheight.js
  modules/ui/fields/roadspeed.js
  package-lock.json
  package.json
Labels: chore-dependency
