Repository openstreetmap/iD, pull requests merged in 2023-08, with the labels that each got.

#9793 fix incorrect earth radius constants
  modules/geo/geo.js
  test/spec/actions/split.js
  test/spec/geo/geo.js
Labels: bug

#9817 don't suggest discardable tags in the raw tag editor
  modules/ui/sections/raw_tag_editor.js
Labels: usability

#9509 Street level photo from the Norwegian Public Road Administration
  CHANGELOG.md
  css/60_photos.css
  data/core.yaml
  modules/renderer/background.js
  modules/renderer/photos.js
  modules/services/index.js
  modules/services/pannellum_photo.js
  modules/services/plane_photo.js
  modules/services/streetside.js
  modules/services/vegbilder.js
  modules/svg/index.js
  modules/svg/kartaview_images.js
  modules/svg/layers.js
  modules/svg/mapilio_images.js
  modules/svg/mapillary_images.js
  modules/svg/mapillary_map_features.js
  modules/svg/mapillary_position.js
  modules/svg/mapillary_signs.js
  modules/svg/streetside.js
  modules/svg/vegbilder.js
  modules/ui/photoviewer.js
  modules/ui/sections/photo_overlays.js
  package.json
  test/spec/services/vegbilder.js
  test/spec/spec_helpers.js
  test/spec/svg/layers.js
Labels: streetlevel

#9826 Update address_formats.json for addr in Ukraine
  data/address_formats.json
Labels: localization

#9849 Hotfix: Fixing Image Width
  css/60_photos.css
Labels: bug
