Repository openstreetmap/iD, pull requests merged in 2023-12, with the labels that each got.

#9990 show date/time for georeferenced photos
  css/60_photos.css
  modules/svg/local_photos.js
Labels: usability, streetlevel

#10007 Sanitize Amazon CloudFront signature in imagery_used
  modules/renderer/background_source.js
  test/spec/renderer/background_source.js
Labels: enhancement

#10002 show empty tag values in multi-selections
  CHANGELOG.md
  css/80_app.css
  data/core.yaml
  modules/ui/sections/raw_tag_editor.js
Labels: enhancement

#9891 Add rendering for roller_coaster=track and roller_coaster=support
  css/50_misc.css
  modules/svg/tag_classes.js
Labels: map-renderer
