Repository openstreetmap/iD, pull requests merged in 2023-11, with the labels that each got.

#9906 Fix regression in user account display (#8813)
  modules/ui/account.js
Labels: bug, bug-release-blocker

#9934 fix esbuild ignoring browserslist config
  config/esbuild.config.min.mjs
  config/esbuild.config.mjs
  package-lock.json
  package.json
Labels: priority, chore-build

#9923 Bump min nodejs to version to v18
  .github/workflows/build.yml
  README.md
  package.json
Labels: chore

#9974 feat(fields/combo): add navigate button to web links in values
  css/80_app.css
  modules/ui/fields/combo.js
Labels: field

#9925 Added address format for Indonesia
  data/address_formats.json
Labels: localization

#9927 Added address format for South Korea
  data/address_formats.json
Labels: localization

#9928 Added address format for Mexico
  data/address_formats.json
Labels: localization

#9685 missing fields in PH address format
  data/address_formats.json
Labels: waitfor-info, localization

#9692 Force colour on Action run
  .github/workflows/build.yml
Labels: chore-build

#9633 fix highway=busway not supported in the turn restriction editor
  modules/osm/intersection.js
  modules/osm/tags.js
  modules/osm/way.js
  modules/svg/lines.js
  modules/ui/fields/access.js
  modules/ui/preset_icon.js
Labels: field

#9424 show (route) relation `colour`s in lists and comboboxes
  CHANGELOG.md
  css/80_app.css
  modules/osm/tags.js
  modules/ui/feature_list.js
  modules/ui/fields/input.js
  modules/ui/sections/raw_member_editor.js
  modules/ui/sections/raw_membership_editor.js
Labels: usability
