Repository openstreetmap/iD, pull requests merged in 2024-12, with the labels that each got.

#10581 Update help panel navigation buttons
  css/80_app.css
Labels: bug

#10582 Restrict direction cones to matching parent ways
  CHANGELOG.md
  modules/osm/node.js
Labels: map-renderer

#10586 Render edit menu to the over-map layer. Fixes #10495
  CHANGELOG.md
  modules/ui/edit_menu.js
  modules/ui/init.js
Labels: bug, usability
