Repository openstreetmap/iD, pull requests merged in 2024-07, with the labels that each got.

#10280 update temaki to v5.9.0
  package-lock.json
  package.json
Labels: chore-dependency

#10046 Add a button in the mapillary image photo viewer to "add the current image id as field to feature"
  CHANGELOG.md
  css/60_photos.css
  data/core.yaml
  modules/services/mapillary.js
  modules/ui/photoviewer.js
Labels: usability, streetlevel

#10317 New Panoramax StreetView Layer (GSOC)
  CHANGELOG.md
  css/60_photos.css
  data/core.yaml
  modules/renderer/background.js
  modules/renderer/photos.js
  modules/services/index.js
  modules/services/pannellum_photo.js
  modules/services/panoramax.js
  modules/services/plane_photo.js
  modules/svg/index.js
  modules/svg/layers.js
  modules/svg/mapilio_images.js
  modules/svg/panoramax_images.js
  modules/ui/photoviewer.js
  test/spec/services/panoramax.js
  test/spec/svg/layers.js
Labels: streetlevel
