Repository openstreetmap/iD, pull requests merged in 2024-03, with the labels that each got.

#10144 Field: Fix html tag type of wikidata label
  modules/ui/fields/wikidata.js
Labels: bug

#10129 Fix for Point Tutorial
  data/core.yaml
  modules/ui/intro/point.js
Labels: walkthrough-help

#10175 Fix roadheight field width
  CHANGELOG.md
  css/80_app.css
Labels: bug, bug-browser-specific, field
