Repository openstreetmap/iD, pull requests merged in 2024-08, with the labels that each got.

#10371 allow to enter strings with quote marks in raw tag editor's text mode
  modules/ui/sections/raw_tag_editor.js
Labels: bug

#10376 Fix panoramax errors when image not in cache
  modules/services/panoramax.js
Labels: bug, streetlevel

#10374 Fix panoramax highlight selected sequence
  modules/services/panoramax.js
  modules/svg/panoramax_images.js
Labels: bug, streetlevel

#10375 Fix panoramax non existing inaccurate sequence
  modules/services/panoramax.js
  modules/svg/panoramax_images.js
  test/spec/services/panoramax.js
Labels: bug, streetlevel

#10385 Fix panoramax blur when switching imagery
  modules/services/pannellum_photo.js
  modules/svg/panoramax_images.js
Labels: bug, streetlevel

#10386 Fix panoramax bubbles stay loaded below minimum zoom
  modules/svg/panoramax_images.js
Labels: bug, streetlevel

#10406 fix eslint not working in IDEs
  eslint.config.mjs
  package.json
Labels: chore-build

#10399 Docs: Remove gif and debugbrowser reference
  CONTRIBUTING.md
Labels: documentation, priority

#10409 configure vscode i18n extension
  .gitignore
  .vscode/extensions.json
  .vscode/i18n-ally-custom-framework.yml
  .vscode/settings.json
Labels: chore

#10397 Docs: Remove reference to mobile
  README.md
Labels: documentation

#10398 Docs: Link to issue "choose" page
  CONTRIBUTING.md
Labels: documentation
