Repository openstreetmap/iD, pull requests merged in 2024-04, with the labels that each got.

#10180 Add links to id tagging schema repository as it is otherwise hard to …
  CONTRIBUTING.md
Labels: documentation

#10209 fix source field link button
  modules/ui/fields/combo.js
Labels: bug, field

#10203 Docs/CONTRIBUTING: Reference readme on how to build
  CONTRIBUTING.md
  README.md
Labels: documentation

#10189 do not remove spaces in inscription after ; sign
  modules/util/clean_tags.js
Labels: bug

#10215 Remove white background from walkthrough tooltip illustrations
  svg/iD-sprite/graphics/graphic-areas.svg
  svg/iD-sprite/graphics/graphic-buildings.svg
  svg/iD-sprite/graphics/graphic-lines.svg
  svg/iD-sprite/graphics/graphic-points.svg
Labels: walkthrough-help

#10205 fix double click bug in note comment
  modules/ui/note_editor.js
Labels: bug

#10181 Sort "more fields" dropdown items
  modules/ui/form_fields.js
Labels: field
