Repository openstreetmap/iD, pull requests merged in 2025-01, with the labels that each got.

#10655 Changed phone number format for Ivory Coast
  data/phone_formats.json
Labels: localization

#10647 use LF line endings for .mjs files
  .editorconfig
  .gitattributes
Labels: chore

#10625 Update dead link
  README.md
Labels: documentation

#10679 fix crash when searching for coordinates
  modules/ui/feature_list.js
Labels: bug

#8042 add queryString option to enable notes by default
  API.md
  modules/svg/notes.js
Labels: api

#9932 fix bug preventing cardinal direction increment
  modules/ui/fields/input.js
Labels: bug

#9933 fix non-integer `layer` tag causing invisible features
  modules/svg/lines.js
  test/spec/svg/lines.js
Labels: bug

#9143 use a more visible colour for oneway arrows on dark lines
  modules/svg/defs.js
  modules/svg/lines.js
  test/spec/svg/lines.js
Labels: usability, map-renderer

#9995 fix backspace not working as a keyboard shortcut
  modules/ui/init.js
Labels: bug-browser-specific

#10674 Update address format for South Korea
  data/address_formats.json
Labels: localization

#10690 fix occasional test failures
  eslint.config.mjs
  test/spec/behavior/hash.js
  test/spec/services/nominatim.js
  test/spec/services/osm.js
  test/spec_helpers.mts
  tsconfig.json
Labels: chore-build

#10684 add indigenous languages not in CLDR
  CHANGELOG.md
  data/languages.json
  data/territory_languages.json
  scripts/build_data.js
  scripts/language_names.js
Labels: localization

#10683 fix confusing behaviour after logging out in the standalone build of iD
  CHANGELOG.md
  modules/services/osm.js
  modules/ui/account.js
Labels: usability

#10712 correct discord channel name in README.md
  README.md
Labels: documentation

#9816 optionally ignore relations in the extract operation
  CHANGELOG.md
  data/core.yaml
  data/shortcuts.json
  modules/actions/extract.js
  modules/behavior/operation.js
  modules/operations/extract.js
  test/spec/actions/extract.js
Labels: operation

#9999 remove rarely-used keyboard shortcut L
  CHANGELOG.md
  data/core.yaml
  data/shortcuts.json
  modules/ui/geolocate.js
Labels: usability

#10716 Improve CJK names with a lang atttribute on multilingual name fields
  CHANGELOG.md
  modules/ui/fields/localized.js
  modules/ui/fields/wikidata.js
  modules/ui/fields/wikipedia.js
  test/spec/ui/fields/localized.js
Labels: localization
