Repository openstreetmap/iD, pull requests merged in 2025-03, with the labels that each got.

#10831 remove `isHighwayIntersection` from osmEntity since it only applies to nodes
  modules/osm/entity.js
  modules/ui/inspector.js
  modules/ui/sections/preset_fields.js
  test/spec/osm/entity.js
Labels: chore

#10834 fix: improve server.js port number logging for better clarity
  scripts/server.js
Labels: bug

#10801 separate tag-upgrade warnings from NSI suggestions
  CHANGELOG.md
  modules/util/util.js
  modules/validations/outdated_tags.js
  test/spec/validations/outdated_tags.js
Labels: bug, validation

#10847 fix: deduplicate postcode suggested
  modules/ui/fields/address.js
Labels: field

#10842 move `deprecatedTags` logic out of osmEntity and into a helper function
  modules/osm/deprecated.js
  modules/osm/entity.js
  modules/ui/fields/combo.js
  modules/validations/outdated_tags.js
  test/spec/osm/deprecated.ts
  test/spec/osm/entity.js
Labels: chore

#10854 fix changelog link
  CHANGELOG.md
Labels: documentation

#10853 Authenticantion in 127.0.0.1 broken / blank screen
  scripts/server.js
Labels: chore

#10805 add alternative formats for coordinate search:
  CHANGELOG.md
  modules/ui/feature_list.js
  modules/util/units.js
  test/spec/util/units.js
Labels: usability

#10865 Feature: add prev/next button to viewer for georeferenced photos
  CHANGELOG.md
  css/60_photos.css
  modules/svg/local_photos.js
Labels: usability

#10703 support localised labels for CLDR overrides
  scripts/language_names.js
Labels: localization, chore-build

#10856 Panoramax: Adopt "copy id" feature from mapillary
  CHANGELOG.md
  modules/services/panoramax.js
  modules/ui/photoviewer.js
  scripts/build_data.js
  svg/fontawesome/fas-cut.svg
  svg/fontawesome/fas-eye-dropper.svg
  test/spec/services/panoramax.js
Labels: streetlevel

#10901 Describe Macau phone format
  data/phone_formats.json
Labels: localization

#10910 consider language scripts when determining the locale to use
  CHANGELOG.md
  modules/core/localizer.js
  test/spec/core/localizer.js
Labels: localization

#10916 Describe-Egypt-phone-format
  CHANGELOG.md
  data/phone_formats.json
Labels: localization
