Repository openstreetmap/iD, pull requests merged in 2025-05, with the labels that each got.

#11015 remove empty line from drag_note.js
  modules/actions/discard_tags.js
  modules/actions/extract.js
  modules/behavior/operation.js
  modules/core/preferences.js
  modules/modes/drag_note.js
  modules/operations/paste.js
  modules/osm/lanes.js
  modules/osm/qa_item.js
  modules/svg/debug.js
  modules/svg/tag_pattern.js
  modules/ui/panes/background.js
  modules/ui/panes/issues.js
  modules/ui/panes/map_data.js
  modules/ui/panes/preferences.js
  modules/util/array.js
  modules/util/detect.js
  modules/util/object.js
Labels: chore

#11027 refresh numeric fields on blur
  CHANGELOG.md
  modules/ui/fields/input.js
Labels: field

#11014 Fix: Mapilio Bubbles
  CHANGELOG.md
  modules/svg/mapilio_images.js
Labels: bug, streetlevel
