Repository openstreetmap/iD, pull requests merged in 2025-07, with the labels that each got.

#11186 chore(tests): don't directly instantiate osmEntity in tests
  test/spec/actions/add_entity.js
  test/spec/actions/change_tags.js
  test/spec/actions/upgrade_tags.js
  test/spec/core/graph.js
  test/spec/osm/entity.js
  test/spec/services/maprules.js
  test/spec/svg/tag_classes.js
Labels: chore

#9317 support quickly adding a direction tag to traffic signs
  CHANGELOG.md
  modules/actions/reverse.js
  test/spec/actions/reverse.js
Labels: usability

#9511 support multiple `prerequisiteTag`s for presets
  CHANGELOG.md
  modules/ui/field.js
Labels: preset

#11222 Fix tile edge blending
  css/80_app.css
Labels: map-renderer

#10639 allow duplicate values in semiCombo for some fields
  CHANGELOG.md
  modules/core/context.js
  modules/globals.d.ts
  modules/ui/fields/combo.js
  test/spec/ui/fields/combo.ts
Labels: field

#11158 Render climbing routes
  CHANGELOG.md
  css/30_highways.css
  css/50_misc.css
  modules/svg/tag_classes.js
  modules/ui/preset_icon.js
  test/spec/renderer/features.js
Labels: map-renderer

#11255 remove the `dev` mailing list from the README
  README.md
Labels: documentation

#11253 make the imagery denylist RegExs case-insensitive
  modules/services/osm.js
  test/spec/services/osm.js
Labels: bug
