Repository openstreetmap/iD, pull requests merged in 2025-02, with the labels that each got.

#10003 prevent degenerate ways caused by deleting a corner of a triangle
  CHANGELOG.md
  modules/osm/way.js
  test/spec/actions/circularize.js
  test/spec/osm/way.js
Labels: bug

#10725 Fix: Show both lat/lon and lon/lat variations in dropdown when searching coordinates
  CHANGELOG.md
  modules/ui/feature_list.js
Labels: usability

#10756 fixed-highlight of bing-streetview and kartaview
  CHANGELOG.md
  css/60_photos.css
Labels: bug, streetlevel

#8808 ways with more than 2000 nodes: prevent lockup and provide validator-fix
  ARCHITECTURE.md
  CHANGELOG.md
  data/core.yaml
  modules/actions/split.js
  modules/validations/index.js
  modules/validations/osm_api_limits.js
  test/spec/actions/split.js
  test/spec/validations/osm_api_limits.js
Labels: bug, validation

#10730 refactor `isOneWay` to properly support bidirectional ways
  modules/osm/index.js
  modules/osm/tags.js
  modules/osm/way.js
  modules/svg/lines.js
  modules/ui/fields/check.js
  modules/util/index.js
  modules/util/object.js
  modules/validations/impossible_oneway.js
  package-lock.json
  package.json
  test/spec/osm/way.js
  test/spec/util/object.js
Labels: chore

#9635 allow broken (unclosed) areas to be continued
  CHANGELOG.md
  modules/operations/continue.js
Labels: operation

#10648 fix relation membership list using a non-deterministic order
  CHANGELOG.md
  modules/actions/join.js
  modules/ui/sections/raw_membership_editor.js
Labels: bug, usability

#10764 Enable autofill for the `source` tag in the changeset panel
  CHANGELOG.md
  modules/ui/changeset_editor.js
  modules/ui/fields/combo.js
Labels: usability

#10728 Include addr:housename in the address schema for Bolivia
  CHANGELOG.md
  data/address_formats.json
Labels: localization

#10763 linkify keys & tags in the preset docs from the wiki
  CHANGELOG.md
  modules/services/osm_wikibase.js
  modules/ui/tag_reference.js
  test/spec/services/osm_wikibase.js
Labels: usability

#10722 use "narrow road" styling for all link roads
  CHANGELOG.md
  css/30_highways.css
Labels: map-renderer

#10768 implement staging build and deploy to netlify
  .github/workflows/staging.yml
  package-lock.json
  package.json
Labels: chore-build

#10767 Improve wording of API.md
  API.md
Labels: documentation

#10737 Don't change direction of red_turn when way is reversed
  CHANGELOG.md
  modules/actions/reverse.js
  test/spec/actions/reverse.js
Labels: bug, operation

#8911 Fix #8758 - Revalidate disconnected_way and impossible_oneway errors on change
  CHANGELOG.md
  modules/core/validator.js
  test/spec/core/validator.js
  test/spec/validations/disconnected_way.js
Labels: bug, validation, priority

#10773 fix conversion of callback-style test runner to promisified one
  test/spec_helpers.mts
Labels: bug, chore-build

#9634 remove `noexit=yes` and `fixme=continue` when you continue a line
  CHANGELOG.md
  modules/operations/continue.js
Labels: usability

#10618 enable IDE auto-completion for the main classes
  CHANGELOG.md
  modules/core/context.js
  modules/core/uploader.js
  modules/core/validator.js
  modules/globals.d.ts
  modules/osm/entity.js
  modules/osm/node.js
  modules/osm/relation.js
  modules/osm/way.js
  modules/renderer/features.js
  modules/util/rebind.js
  test/spec/util/rebind.js
Labels: documentation

#9522 validate suspicious names using the user's language
  CHANGELOG.md
  modules/validations/suspicious_name.js
  test/spec/validations/suspicious_name.js
Labels: validation

#10781 mass-replace the `done()` function with async/await in unit tests
  package-lock.json
  package.json
  test/spec/behavior/hash.js
  test/spec/behavior/select.js
  test/spec/core/LocationManager.js
  test/spec/core/file_fetcher.js
  test/spec/core/history.js
  test/spec/core/validator.js
  test/spec/presets/index.js
  test/spec/renderer/map.js
  test/spec/services/kartaview.js
  test/spec/services/nominatim.js
  test/spec/services/osm.js
  test/spec/services/osm_wikibase.js
  test/spec/services/streetside.js
  test/spec/services/taginfo.js
  test/spec/services/vegbilder.js
  test/spec/svg/data.js
  test/spec/ui/combobox.js
  test/spec/ui/confirm.js
  test/spec/ui/fields/localized.js
  test/spec/ui/fields/wikipedia.js
  test/spec/ui/flash.js
  test/spec/ui/modal.js
  test/spec/ui/sections/raw_tag_editor.js
  test/spec/validations/mutually_exclusive_tags.js
  test/spec/validations/outdated_tags.js
  test/spec/validations/suspicious_name.js
  test/spec_helpers.mts
Labels: chore-build

#9504 fix tile stacking order
  modules/renderer/tile_layer.js
Labels: map-renderer, enhancement

#10798 Always use HTTPS to load Bing Streetside images
  CHANGELOG.md
  modules/services/streetside.js
Labels: streetlevel

#10799 Fix duplicate values in the `source` field on the changeset page
  modules/ui/changeset_editor.js
Labels: bug

#10819 Change zoomToNote to moveToNote
  modules/behavior/hash.js
  modules/core/context.js
  modules/ui/feature_list.js
Labels: usability
