Repository openstreetmap/iD, pull requests merged in 2025-04, with the labels that each got.

#10949 suggest housenumber/housename values from surrounding areas
  CHANGELOG.md
  modules/ui/fields/address.js
Labels: usability, field

#10943 only consider proper lifecycle tagging in "past/futures" layer
  CHANGELOG.md
  modules/renderer/features.js
  test/spec/renderer/features.js
Labels: bug

#10942 disambiguate relations with same names in membership editor
  CHANGELOG.md
  modules/ui/sections/raw_membership_editor.js
Labels: usability

#10926 fix: merging two ways corrupts step_count
  CHANGELOG.md
  modules/actions/join.js
  modules/actions/split.js
  modules/osm/entity.js
  modules/osm/tags.js
  test/spec/actions/join.js
  test/spec/actions/split.js
  test/spec/osm/entity.js
Labels: operation
